# Site settings
# YAML cheat sheet: https://quickref.me/yaml

title: "Living Life"
description: "A template for building a fast Eleventy blog with Sveltia CMS, for deployment to Netlify"
url: "https://sveltia.paulapplegate.com"